const createEntityController = require('../../../controllers/entity.controller');
const { createEntityRoutes, text, body } = require('./entity.routes');

const resources = {
  manufacturers: { model: 'manufacturer', label: 'Manufacturer', fields: ['name', 'country'], rules: [text('name', true), text('country')], sortable: ['name', 'country', 'createdAt'] },
  categories: { model: 'category', label: 'Category', fields: ['name', 'description'], rules: [text('name', true), text('description')], sortable: ['name', 'createdAt'] },
  'active-ingredients': { model: 'activeIngredient', label: 'Active ingredient', fields: ['name'], rules: [text('name', true)], sortable: ['name', 'createdAt'] },
  organizations: { model: 'managingOrganization', label: 'Organization', fields: ['code', 'name', 'website', 'phone'], rules: [text('code', true), text('name', true), body('website').optional({ nullable: true }).isURL(), text('phone')], searchable: ['name', 'code'], sortable: ['name', 'code', 'createdAt'] },
  regimes: { model: 'regime', label: 'Regime', fields: ['code', 'name', 'description'], rules: [text('code', true), text('name', true), text('description')], searchable: ['name', 'code'], sortable: ['name', 'code', 'createdAt'] },
  sources: { model: 'source', label: 'Source', fields: ['code', 'name', 'description', 'website'], rules: [text('code', true), text('name', true), text('description'), body('website').optional({ nullable: true }).isURL()], searchable: ['name', 'code'], sortable: ['name', 'code', 'createdAt'] },
  'source-resources': { model: 'sourceResource', label: 'Source resource', fields: ['name', 'url', 'fileHash', 'publishedAt', 'sourceId'], rules: [text('name', true), body('sourceId').isInt({ min: 1 }).toInt(), body('url').optional({ nullable: true }).isURL(), text('fileHash'), body('publishedAt').optional({ nullable: true }).isISO8601().toDate()], includes: { source: true }, searchable: ['name'], sortable: ['name', 'publishedAt', 'createdAt'] },
  'official-documents': { model: 'officialDocument', label: 'Official document', fields: ['title', 'reference', 'url', 'publishedAt'], rules: [text('title', true), text('reference'), body('url').optional({ nullable: true }).isURL(), body('publishedAt').optional({ nullable: true }).isISO8601().toDate()], searchable: ['title', 'reference'], sortable: ['title', 'publishedAt', 'createdAt'] },
  'medication-prices': { model: 'medicationPrice', label: 'Medication price', fields: ['medicationId', 'publicPrice', 'hospitalPrice', 'effectiveDate'], rules: [body('medicationId').isInt({ min: 1 }).toInt(), body('publicPrice').optional({ nullable: true }).isFloat({ min: 0 }).toFloat(), body('hospitalPrice').optional({ nullable: true }).isFloat({ min: 0 }).toFloat(), body('effectiveDate').optional({ nullable: true }).isISO8601().toDate()], includes: { medication: true }, searchable: [], sortable: ['effectiveDate', 'createdAt'] },
  reimbursements: { model: 'reimbursement', label: 'Reimbursement', fields: ['medicationId', 'organizationId', 'regimeId', 'documentId', 'reimbursementBase', 'reimbursementRate', 'referencePrice', 'conditions', 'status'], rules: [body('medicationId').isInt({ min: 1 }).toInt(), body('organizationId').isInt({ min: 1 }).toInt(), body('regimeId').optional({ nullable: true }).isInt({ min: 1 }).toInt(), body('documentId').optional({ nullable: true }).isInt({ min: 1 }).toInt(), body('reimbursementBase').optional({ nullable: true }).isFloat({ min: 0 }).toFloat(), body('reimbursementRate').optional({ nullable: true }).isFloat({ min: 0, max: 100 }).toFloat(), body('referencePrice').optional({ nullable: true }).isFloat({ min: 0 }).toFloat(), text('conditions'), body('status').optional().isIn(['ACTIVE', 'ARCHIVED'])], includes: { medication: true, organization: true, regime: true, document: true }, searchable: [], sortable: ['createdAt', 'updatedAt'], archive: true },
  'sync-jobs': { model: 'syncJob', label: 'Sync job', fields: ['status', 'sourceId', 'resourceId', 'recordsRead', 'recordsValid', 'recordsRejected', 'recordsCreated', 'recordsUpdated', 'recordsDuplicates', 'errorsCount', 'errorDetails', 'completedAt'], rules: [text('status', true), body('sourceId').isInt({ min: 1 }).toInt()], includes: { source: true, resource: true }, searchable: [], sortable: ['startedAt', 'completedAt', 'createdAt'] },
};

module.exports = Object.fromEntries(Object.entries(resources).map(([path, config]) => [path, createEntityRoutes(createEntityController(config), config.rules)]));
